/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlbhcafe.view.form.banhang;

import com.qlbhcafe.helper.Designhelper;
import static com.qlbhcafe.helper.Designhelper.bruteforce;
import com.qlbhcafe.model.CTHoaDon;
import com.qlbhcafe.model.HoaDon;
import com.qlbhcafe.model.SanPham;
import com.qlbhcafe.test.testSQL;
import com.qlbhcafe.view.form.banhang.FormBanHang;
import static com.qlbhcafe.view.form.banhang.FormBanHang.DongCTHD;
import static com.qlbhcafe.view.form.banhang.FormBanHang.jpldonhang;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author baotri1998
 */
public class Datmon extends javax.swing.JDialog {

    /**
     * Creates new form Datmon
     */
    public Datmon(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    String maString, ten, gia, img, soluong;
    public List<CTHoaDon> list1;
    public List<SanPham> showSP = null;

    int so = 0;
    public static Datmon datmon;

    public Datmon(java.awt.Frame parent, boolean modal, String ma, String gia, String ten, String img, String soluong) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.maString = ma;
        this.gia = gia;
        this.ten = ten;
        this.img = img;
        this.soluong = soluong;
        datmon = this;
        lblgia.setText(this.gia);
        lblten.setName(maString);
        lblten.setText(this.ten);
      

        fill();

    }

    public Datmon(java.awt.Frame parent, boolean modal, String ma, String gia, String ten, String img) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.maString = ma;
        this.gia = gia;
        this.ten = ten;
        this.img = img;
        datmon = this;
        lblgia.setText(this.gia);
        lblten.setName(maString);
        lblten.setText(this.ten);
     
        fill();

    }

    public void getCTHD() {
        list1 = new ArrayList<CTHoaDon>();
        CTHoaDon ct = new CTHoaDon();
        SanPham sp = new SanPham();
        sp.setTenSp(lblten.getText());
        sp.setMaSP(lblten.getName());
        sp.setGiaBan(Double.parseDouble(lblgia.getText()));
        sp.setExtra(txtGhichu.getText());
        sp.setHinhAnh("/com/qlbhcafe/img/" + lblimg.getText());
        //getClass().getResource("/com/qlbhcafe/img/" + data.get(i).getHinhAnh()))
        ct.setSoLuong(Integer.parseInt(txtdatmon.getText()));
        ct.setMaSanPham(sp);

        list1.add(ct);
    }

    public void DongGoi() {
        CTHoaDon cthd = new CTHoaDon();
        SanPham sp = new SanPham();
        for (int i = 0; i < Datmon.datmon.list1.size(); i++) {
            sp.setMaSP(Datmon.datmon.list1.get(i).getMaSanPham().getMaSP());
            sp.setTenSp(Datmon.datmon.list1.get(i).getMaSanPham().getTenSp());
            sp.setGiaBan(Datmon.datmon.list1.get(i).getMaSanPham().getGiaBan());
            sp.setExtra(Datmon.datmon.list1.get(i).getMaSanPham().getExtra());
            sp.setHinhAnh(Datmon.datmon.list1.get(i).getMaSanPham().getHinhAnh());
            cthd.setSoLuong(Datmon.datmon.list1.get(i).getSoLuong());
            cthd.setMaSanPham(sp);
        }
        DongCTHD.add(cthd);
    }

    public void fill() {
        showSP = testSQL.FindmaSP(maString);
        lblmaSP.setText(showSP.get(0).getMaSP());
        lblten.setName(showSP.get(0).getMaSP());
        lblten.setText(showSP.get(0).getTenSp());
        lblgia.setText(String.valueOf(showSP.get(0).getGiaBan()));
        lblimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbhcafe/img/" + showSP.get(0).getHinhAnh())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtdatmon = new javax.swing.JTextField();
        lblten = new javax.swing.JLabel();
        lbltengia = new javax.swing.JLabel();
        lblimg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGhichu = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblgia = new javax.swing.JLabel();
        lblbutonTat = new javax.swing.JLabel();
        lblbutonThem = new javax.swing.JLabel();
        lblmaSP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtdatmon.setText("1");

        lblten.setBackground(new java.awt.Color(51, 0, 255));
        lblten.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblten.setForeground(new java.awt.Color(255, 255, 255));
        lblten.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblten.setText("tên:");
        lblten.setOpaque(true);

        lbltengia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbltengia.setText("Giá");

        lblimg.setBackground(new java.awt.Color(255, 255, 255));
        lblimg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblimg.setAutoscrolls(true);
        lblimg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblimg.setOpaque(true);

        txtGhichu.setColumns(20);
        txtGhichu.setRows(5);
        jScrollPane1.setViewportView(txtGhichu);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("SL:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Ghi Chú:");

        lblgia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblgia.setText("....");

        lblbutonTat.setBackground(new java.awt.Color(51, 51, 255));
        lblbutonTat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblbutonTat.setForeground(new java.awt.Color(255, 255, 255));
        lblbutonTat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblbutonTat.setText("Tắt");
        lblbutonTat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblbutonTat.setOpaque(true);
        lblbutonTat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblbutonTatMousePressed(evt);
            }
        });

        lblbutonThem.setBackground(new java.awt.Color(51, 51, 255));
        lblbutonThem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblbutonThem.setForeground(new java.awt.Color(255, 255, 255));
        lblbutonThem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblbutonThem.setText("Cập Nhật Vào Giỏ");
        lblbutonThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblbutonThem.setOpaque(true);
        lblbutonThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblbutonThemMousePressed(evt);
            }
        });

        lblmaSP.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lblmaSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblbutonThem, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(lblbutonTat, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblimg, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblmaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtdatmon, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbltengia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblgia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(lblten, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblten, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtdatmon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3)
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblgia)
                            .addComponent(lbltengia)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblimg, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblmaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblbutonThem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblbutonTat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void lblbutonThemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbutonThemMousePressed
        // TODO add your handling code here:
        /*for (Iterator<CTHoaDon> i = DongCTHD.iterator(); i.hasNext();) {
            CTHoaDon a = i.next();
            if (a.getSanPham().getMaSP().equalsIgnoreCase(String.valueOf(lblten.getName()))) {
                i.remove();
            }

        }*/
       
     
        getCTHD();
        DongGoi();
        dispose();

    }//GEN-LAST:event_lblbutonThemMousePressed

    private void lblbutonTatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbutonTatMousePressed
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_lblbutonTatMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Datmon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Datmon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Datmon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Datmon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Datmon dialog = new Datmon(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblbutonTat;
    private javax.swing.JLabel lblbutonThem;
    private javax.swing.JLabel lblgia;
    private javax.swing.JLabel lblimg;
    private javax.swing.JLabel lblmaSP;
    private javax.swing.JLabel lblten;
    private javax.swing.JLabel lbltengia;
    private javax.swing.JTextArea txtGhichu;
    public static javax.swing.JTextField txtdatmon;
    // End of variables declaration//GEN-END:variables
}
