/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlbhcafe.view.form.khachhang;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author baotri1998
 */
public class DanhSachHoiVien extends javax.swing.JPanel {

    /**
     * Creates new form FormDanhSachHoiVien
     */
    public DanhSachHoiVien() {
        initComponents();
        tblKhachHang2.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 13));
        tblKhachHang2.setFont(new Font("Tohoma", Font.PLAIN, 12));
        tblKhachHang2.getTableHeader().setOpaque(false);
        tblKhachHang2.getTableHeader().setBackground(new Color(0, 0, 0));
        tblKhachHang2.getTableHeader().setForeground(new Color(255, 255, 255));
        tblKhachHang2.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnDShoivien = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblKhachHang2 = new javax.swing.JTable();

        jpnDShoivien.setLayout(new java.awt.CardLayout());

        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        tblKhachHang2.setForeground(new java.awt.Color(51, 51, 51));
        tblKhachHang2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Khách Hàng", "Tên", "Địa Chỉ", "Điện Thoại", "Điểm Thưởng", "Dư Nợ"
            }
        ));
        tblKhachHang2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblKhachHang2.setFocusable(false);
        tblKhachHang2.setGridColor(new java.awt.Color(0, 0, 0));
        tblKhachHang2.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblKhachHang2.setRowHeight(25);
        tblKhachHang2.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblKhachHang2.setShowHorizontalLines(false);
        tblKhachHang2.setShowVerticalLines(false);
        tblKhachHang2.setSurrendersFocusOnKeystroke(true);
        tblKhachHang2.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tblKhachHang2);

        jpnDShoivien.add(jScrollPane3, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpnDShoivien, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpnDShoivien, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel jpnDShoivien;
    private javax.swing.JTable tblKhachHang2;
    // End of variables declaration//GEN-END:variables
}
