/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nhom3.qlcf.view.form.khachhang;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author baotri1998
 */
public class KhachHangOnline extends javax.swing.JPanel {

    /**
     * Creates new form FormKhachHangOnline
     */
    public KhachHangOnline() {
        initComponents();
            
     tblKhachHang1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 13));
        tblKhachHang1.setFont(new Font("Tohoma", Font.PLAIN, 12));
        tblKhachHang1.getTableHeader().setOpaque(false);
        tblKhachHang1.getTableHeader().setBackground(new Color(0, 0, 0));
        tblKhachHang1.getTableHeader().setForeground(new Color(255, 255, 255));
        tblKhachHang1.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnKHonline = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKhachHang1 = new javax.swing.JTable();

        jpnKHonline.setLayout(new java.awt.CardLayout());

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        tblKhachHang1.setForeground(new java.awt.Color(51, 51, 51));
        tblKhachHang1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Khách Hàng", "Tên", "Địa Chỉ Ship", "Điện Thoại", "Trạng Thái"
            }
        ));
        tblKhachHang1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblKhachHang1.setFocusable(false);
        tblKhachHang1.setGridColor(new java.awt.Color(0, 0, 0));
        tblKhachHang1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblKhachHang1.setRowHeight(25);
        tblKhachHang1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblKhachHang1.setShowHorizontalLines(false);
        tblKhachHang1.setShowVerticalLines(false);
        tblKhachHang1.setSurrendersFocusOnKeystroke(true);
        tblKhachHang1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblKhachHang1);

        jpnKHonline.add(jScrollPane2, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpnKHonline, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpnKHonline, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpnKHonline;
    private javax.swing.JTable tblKhachHang1;
    // End of variables declaration//GEN-END:variables
}
