/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nhom3.qlcf.view.form.menu;

import com.nhom3.qlcf.helper.Soundhelper;
import com.nhom3.qlcf.view.form.hanghoa.FormKiemTraHangHoa;
import com.nhom3.qlcf.view.form.hanghoa.FormNhapThemHangHoa;
import com.nhom3.qlcf.view.form.hanghoa.FormSuaHangHoa_admin;
import com.nhom3.qlcf.view.form.banhang.FormBanHang;
import com.nhom3.qlcf.view.form.doanhthu.FormDonHang;
import com.nhom3.qlcf.view.form.doanhthu.FormThongKe;
import com.nhom3.qlcf.view.form.hanghoa.FormQuanLyPhieuNhap_admin;
import com.nhom3.qlcf.view.form.login.FormLogin;
import com.nhom3.qlcf.view.form.khachhang.FormKhachHang;
import com.nhom3.qlcf.view.form.login.Login;
import com.nhom3.qlcf.view.form.nhacungcap.FormDanhSachNhaCC;
import com.nhom3.qlcf.view.form.nhacungcap.FormThemNhaCungCap_admin;
import com.nhom3.qlcf.view.form.sanpham.FormThemSanPham;
import com.nhom3.qlcf.view.form.users.FormQuanLyTaiKhoan_admin;
import com.nhom3.qlcf.view.form.users.FormTaiKhoan;
import java.awt.Color;
import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;

/**
 *
 * @author baotri1998
 */
public class FormMenu extends javax.swing.JPanel {

    /**
     * Creates new form FormMenu
     */
    public static FormMenu trangchu;
    Soundhelper mp3;

    public FormMenu() {
        initComponents();
        trangchu = this;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfMain = new javax.swing.JPanel();
        jpnShowMenuOut = new javax.swing.JPanel();
        jpnDangXuat = new javax.swing.JPanel();
        lblDangXuat = new javax.swing.JLabel();
        jpnTenDangNhap = new javax.swing.JPanel();
        lblTenDangNhap = new javax.swing.JLabel();
        jlbLogo150px2 = new javax.swing.JLabel();
        jpnMenu4 = new javax.swing.JPanel();
        jpnThemNhaCungCap_Button = new javax.swing.JPanel();
        lblThemNhaCungCap = new javax.swing.JLabel();
        lblThemNhaCungCap_txt = new javax.swing.JLabel();
        jpnSuaXoaSP_Button = new javax.swing.JPanel();
        lblSuaXoaSP = new javax.swing.JLabel();
        lblSuaXoaSP_txt = new javax.swing.JLabel();
        jpnMenu3 = new javax.swing.JPanel();
        jpnTaiKhoan_Button = new javax.swing.JPanel();
        lblTaiKhoan = new javax.swing.JLabel();
        lblTaiKhoan_txt = new javax.swing.JLabel();
        jpnQuanLyTaiKhoan_Button = new javax.swing.JPanel();
        lblQuanLyTaiKhoan = new javax.swing.JLabel();
        lblQuanLyTaiKhoan_txt = new javax.swing.JLabel();
        jpnSuaHangHoa_Button = new javax.swing.JPanel();
        lblSuaHangHoa_Button = new javax.swing.JLabel();
        lblSuaHangHoa_txt = new javax.swing.JLabel();
        jpnPhieuNhap_Button = new javax.swing.JPanel();
        lblPhieuNhap = new javax.swing.JLabel();
        lblPhieuNhap_txt = new javax.swing.JLabel();
        jpnMenu2 = new javax.swing.JPanel();
        jpnNhaCungCap_Button = new javax.swing.JPanel();
        lblNhacungcap = new javax.swing.JLabel();
        lblNhaCungCap_txt = new javax.swing.JLabel();
        jpnKhachHang_Button = new javax.swing.JPanel();
        lblKhachHang = new javax.swing.JLabel();
        lblKhachHang_txt = new javax.swing.JLabel();
        jpnHoaDon_Button = new javax.swing.JPanel();
        lblHoaDon = new javax.swing.JLabel();
        lblHoaDon_txt = new javax.swing.JLabel();
        jpnBieuDo_Button = new javax.swing.JPanel();
        lblBieuDo = new javax.swing.JLabel();
        lblBieudo_txt = new javax.swing.JLabel();
        jpnMenu1 = new javax.swing.JPanel();
        jpnBanHang_Button = new javax.swing.JPanel();
        lblBanHang = new javax.swing.JLabel();
        lblBanHang_txt = new javax.swing.JLabel();
        jpnKienTra_Button = new javax.swing.JPanel();
        lblKiemTra = new javax.swing.JLabel();
        lblKiemTraHangHoa_txt = new javax.swing.JLabel();
        jpnNhapHanghoa_Button = new javax.swing.JPanel();
        lblThemHangHoa = new javax.swing.JLabel();
        lblthemHangHoa_txt = new javax.swing.JLabel();
        jpnThemSP_Button = new javax.swing.JPanel();
        lblThemSanPham = new javax.swing.JLabel();
        lblThemsanPham_txt = new javax.swing.JLabel();
        jpnToolbar2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblOut = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Card = new javax.swing.JPanel();

        setOpaque(false);
        setLayout(new java.awt.CardLayout());

        jfMain.setBackground(new java.awt.Color(255, 153, 153));
        jfMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnShowMenuOut.setBackground(new java.awt.Color(255, 255, 255));
        jpnShowMenuOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnShowMenuOutMouseExited(evt);
            }
        });
        jpnShowMenuOut.setLayout(null);

        jpnDangXuat.setBackground(new java.awt.Color(255, 255, 255));

        lblDangXuat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDangXuat.setForeground(new java.awt.Color(51, 102, 255));
        lblDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDangXuat.setText("Đăng Xuất");
        lblDangXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpnDangXuatLayout = new javax.swing.GroupLayout(jpnDangXuat);
        jpnDangXuat.setLayout(jpnDangXuatLayout);
        jpnDangXuatLayout.setHorizontalGroup(
            jpnDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jpnDangXuatLayout.setVerticalGroup(
            jpnDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jpnShowMenuOut.add(jpnDangXuat);
        jpnDangXuat.setBounds(10, 50, 150, 40);

        jpnTenDangNhap.setBackground(new java.awt.Color(255, 255, 255));

        lblTenDangNhap.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTenDangNhap.setForeground(new java.awt.Color(51, 102, 255));
        lblTenDangNhap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenDangNhap.setText("Tên NV");
        lblTenDangNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTenDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTenDangNhapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTenDangNhapMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpnTenDangNhapLayout = new javax.swing.GroupLayout(jpnTenDangNhap);
        jpnTenDangNhap.setLayout(jpnTenDangNhapLayout);
        jpnTenDangNhapLayout.setHorizontalGroup(
            jpnTenDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTenDangNhapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTenDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnTenDangNhapLayout.setVerticalGroup(
            jpnTenDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTenDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jpnShowMenuOut.add(jpnTenDangNhap);
        jpnTenDangNhap.setBounds(10, 9, 150, 40);

        jfMain.add(jpnShowMenuOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, 170, 100));
        jpnShowMenuOut.hide();

        jlbLogo150px2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/logoCafe100px.png"))); // NOI18N
        jfMain.add(jlbLogo150px2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 100));

        jpnMenu4.setOpaque(false);

        jpnThemNhaCungCap_Button.setOpaque(false);

        lblThemNhaCungCap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThemNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/iconThemNhacungcap120px.png"))); // NOI18N
        lblThemNhaCungCap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblThemNhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblThemNhaCungCapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThemNhaCungCapMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblThemNhaCungCapMousePressed(evt);
            }
        });

        lblThemNhaCungCap_txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblThemNhaCungCap_txt.setForeground(new java.awt.Color(255, 255, 255));
        lblThemNhaCungCap_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThemNhaCungCap_txt.setText("Thêm Nhà Cung Cấp");
        lblThemNhaCungCap_txt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpnThemNhaCungCap_ButtonLayout = new javax.swing.GroupLayout(jpnThemNhaCungCap_Button);
        jpnThemNhaCungCap_Button.setLayout(jpnThemNhaCungCap_ButtonLayout);
        jpnThemNhaCungCap_ButtonLayout.setHorizontalGroup(
            jpnThemNhaCungCap_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblThemNhaCungCap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblThemNhaCungCap_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnThemNhaCungCap_ButtonLayout.setVerticalGroup(
            jpnThemNhaCungCap_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThemNhaCungCap_ButtonLayout.createSequentialGroup()
                .addComponent(lblThemNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblThemNhaCungCap_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpnSuaXoaSP_Button.setOpaque(false);

        lblSuaXoaSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/iconsuaXoaSP120px.png"))); // NOI18N
        lblSuaXoaSP.setToolTipText("");
        lblSuaXoaSP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSuaXoaSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSuaXoaSPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSuaXoaSPMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSuaXoaSPMousePressed(evt);
            }
        });

        lblSuaXoaSP_txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSuaXoaSP_txt.setForeground(new java.awt.Color(255, 255, 255));
        lblSuaXoaSP_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSuaXoaSP_txt.setText("Sửa/ Xóa Sản Phẩm");
        lblSuaXoaSP_txt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpnSuaXoaSP_ButtonLayout = new javax.swing.GroupLayout(jpnSuaXoaSP_Button);
        jpnSuaXoaSP_Button.setLayout(jpnSuaXoaSP_ButtonLayout);
        jpnSuaXoaSP_ButtonLayout.setHorizontalGroup(
            jpnSuaXoaSP_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSuaXoaSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblSuaXoaSP_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnSuaXoaSP_ButtonLayout.setVerticalGroup(
            jpnSuaXoaSP_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSuaXoaSP_ButtonLayout.createSequentialGroup()
                .addComponent(lblSuaXoaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSuaXoaSP_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jpnMenu4Layout = new javax.swing.GroupLayout(jpnMenu4);
        jpnMenu4.setLayout(jpnMenu4Layout);
        jpnMenu4Layout.setHorizontalGroup(
            jpnMenu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenu4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jpnMenu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnThemNhaCungCap_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnSuaXoaSP_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jpnMenu4Layout.setVerticalGroup(
            jpnMenu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenu4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jpnSuaXoaSP_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnThemNhaCungCap_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );

        jfMain.add(jpnMenu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 40, 220, 650));

        jpnMenu3.setOpaque(false);

        jpnTaiKhoan_Button.setOpaque(false);

        lblTaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/iconUser120px.png"))); // NOI18N
        lblTaiKhoan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTaiKhoanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTaiKhoanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblTaiKhoanMousePressed(evt);
            }
        });

        lblTaiKhoan_txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTaiKhoan_txt.setForeground(new java.awt.Color(255, 255, 255));
        lblTaiKhoan_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTaiKhoan_txt.setText("Tài Khoản ");
        lblTaiKhoan_txt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpnTaiKhoan_ButtonLayout = new javax.swing.GroupLayout(jpnTaiKhoan_Button);
        jpnTaiKhoan_Button.setLayout(jpnTaiKhoan_ButtonLayout);
        jpnTaiKhoan_ButtonLayout.setHorizontalGroup(
            jpnTaiKhoan_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTaiKhoan_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
        );
        jpnTaiKhoan_ButtonLayout.setVerticalGroup(
            jpnTaiKhoan_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTaiKhoan_ButtonLayout.createSequentialGroup()
                .addComponent(lblTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTaiKhoan_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpnQuanLyTaiKhoan_Button.setOpaque(false);

        lblQuanLyTaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuanLyTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/iconQuanLyTK120px.png"))); // NOI18N
        lblQuanLyTaiKhoan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblQuanLyTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuanLyTaiKhoanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuanLyTaiKhoanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblQuanLyTaiKhoanMousePressed(evt);
            }
        });

        lblQuanLyTaiKhoan_txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblQuanLyTaiKhoan_txt.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanLyTaiKhoan_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuanLyTaiKhoan_txt.setText("Quản Lý Tài Khoản");
        lblQuanLyTaiKhoan_txt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpnQuanLyTaiKhoan_ButtonLayout = new javax.swing.GroupLayout(jpnQuanLyTaiKhoan_Button);
        jpnQuanLyTaiKhoan_Button.setLayout(jpnQuanLyTaiKhoan_ButtonLayout);
        jpnQuanLyTaiKhoan_ButtonLayout.setHorizontalGroup(
            jpnQuanLyTaiKhoan_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQuanLyTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblQuanLyTaiKhoan_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnQuanLyTaiKhoan_ButtonLayout.setVerticalGroup(
            jpnQuanLyTaiKhoan_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQuanLyTaiKhoan_ButtonLayout.createSequentialGroup()
                .addComponent(lblQuanLyTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQuanLyTaiKhoan_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpnSuaHangHoa_Button.setOpaque(false);

        lblSuaHangHoa_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/iconChinhSuaHangHoa150px.png"))); // NOI18N
        lblSuaHangHoa_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSuaHangHoa_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSuaHangHoa_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSuaHangHoa_ButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSuaHangHoa_ButtonMousePressed(evt);
            }
        });

        lblSuaHangHoa_txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSuaHangHoa_txt.setForeground(new java.awt.Color(255, 255, 255));
        lblSuaHangHoa_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSuaHangHoa_txt.setText("Chỉnh Sữa Hàng Hóa");
        lblSuaHangHoa_txt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpnSuaHangHoa_ButtonLayout = new javax.swing.GroupLayout(jpnSuaHangHoa_Button);
        jpnSuaHangHoa_Button.setLayout(jpnSuaHangHoa_ButtonLayout);
        jpnSuaHangHoa_ButtonLayout.setHorizontalGroup(
            jpnSuaHangHoa_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSuaHangHoa_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
            .addComponent(lblSuaHangHoa_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnSuaHangHoa_ButtonLayout.setVerticalGroup(
            jpnSuaHangHoa_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSuaHangHoa_ButtonLayout.createSequentialGroup()
                .addComponent(lblSuaHangHoa_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSuaHangHoa_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpnPhieuNhap_Button.setOpaque(false);

        lblPhieuNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/iconPhieuNhap120px.png"))); // NOI18N
        lblPhieuNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPhieuNhapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPhieuNhapMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblPhieuNhapMousePressed(evt);
            }
        });

        lblPhieuNhap_txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPhieuNhap_txt.setForeground(new java.awt.Color(255, 255, 255));
        lblPhieuNhap_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhieuNhap_txt.setText("Quản Lý Phiếu Nhập");
        lblPhieuNhap_txt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpnPhieuNhap_ButtonLayout = new javax.swing.GroupLayout(jpnPhieuNhap_Button);
        jpnPhieuNhap_Button.setLayout(jpnPhieuNhap_ButtonLayout);
        jpnPhieuNhap_ButtonLayout.setHorizontalGroup(
            jpnPhieuNhap_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPhieuNhap_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnPhieuNhap_ButtonLayout.createSequentialGroup()
                .addComponent(lblPhieuNhap)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpnPhieuNhap_ButtonLayout.setVerticalGroup(
            jpnPhieuNhap_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPhieuNhap_ButtonLayout.createSequentialGroup()
                .addComponent(lblPhieuNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPhieuNhap_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jpnMenu3Layout = new javax.swing.GroupLayout(jpnMenu3);
        jpnMenu3.setLayout(jpnMenu3Layout);
        jpnMenu3Layout.setHorizontalGroup(
            jpnMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenu3Layout.createSequentialGroup()
                .addGroup(jpnMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnMenu3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpnPhieuNhap_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnMenu3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jpnMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpnMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jpnSuaHangHoa_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jpnQuanLyTaiKhoan_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpnMenu3Layout.createSequentialGroup()
                                .addComponent(jpnTaiKhoan_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jpnMenu3Layout.setVerticalGroup(
            jpnMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenu3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnTaiKhoan_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnQuanLyTaiKhoan_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnSuaHangHoa_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnPhieuNhap_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jfMain.add(jpnMenu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 230, 660));

        jpnMenu2.setOpaque(false);

        jpnNhaCungCap_Button.setOpaque(false);

        lblNhacungcap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNhacungcap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/iconNhacungcap120px.png"))); // NOI18N
        lblNhacungcap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNhacungcap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNhacungcapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNhacungcapMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblNhacungcapMousePressed(evt);
            }
        });

        lblNhaCungCap_txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNhaCungCap_txt.setForeground(new java.awt.Color(255, 255, 255));
        lblNhaCungCap_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNhaCungCap_txt.setText("Danh Sách Nhà Cung Cấp");
        lblNhaCungCap_txt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpnNhaCungCap_ButtonLayout = new javax.swing.GroupLayout(jpnNhaCungCap_Button);
        jpnNhaCungCap_Button.setLayout(jpnNhaCungCap_ButtonLayout);
        jpnNhaCungCap_ButtonLayout.setHorizontalGroup(
            jpnNhaCungCap_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNhaCungCap_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(lblNhacungcap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnNhaCungCap_ButtonLayout.setVerticalGroup(
            jpnNhaCungCap_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNhaCungCap_ButtonLayout.createSequentialGroup()
                .addComponent(lblNhacungcap, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNhaCungCap_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpnKhachHang_Button.setOpaque(false);

        lblKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/iconDanhsachKH120px.png"))); // NOI18N
        lblKhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKhachHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblKhachHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblKhachHangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblKhachHangMousePressed(evt);
            }
        });

        lblKhachHang_txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblKhachHang_txt.setForeground(new java.awt.Color(255, 255, 255));
        lblKhachHang_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKhachHang_txt.setText("Danh Sách KH");
        lblKhachHang_txt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpnKhachHang_ButtonLayout = new javax.swing.GroupLayout(jpnKhachHang_Button);
        jpnKhachHang_Button.setLayout(jpnKhachHang_ButtonLayout);
        jpnKhachHang_ButtonLayout.setHorizontalGroup(
            jpnKhachHang_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
            .addComponent(lblKhachHang_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnKhachHang_ButtonLayout.setVerticalGroup(
            jpnKhachHang_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnKhachHang_ButtonLayout.createSequentialGroup()
                .addComponent(lblKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(lblKhachHang_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpnHoaDon_Button.setOpaque(false);

        lblHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/iconDanhSachDonHang120px.png"))); // NOI18N
        lblHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHoaDonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHoaDonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblHoaDonMousePressed(evt);
            }
        });

        lblHoaDon_txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHoaDon_txt.setForeground(new java.awt.Color(255, 255, 255));
        lblHoaDon_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHoaDon_txt.setText("Danh Sách Đơn Hàng");
        lblHoaDon_txt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpnHoaDon_ButtonLayout = new javax.swing.GroupLayout(jpnHoaDon_Button);
        jpnHoaDon_Button.setLayout(jpnHoaDon_ButtonLayout);
        jpnHoaDon_ButtonLayout.setHorizontalGroup(
            jpnHoaDon_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblHoaDon_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnHoaDon_ButtonLayout.setVerticalGroup(
            jpnHoaDon_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHoaDon_ButtonLayout.createSequentialGroup()
                .addComponent(lblHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHoaDon_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpnBieuDo_Button.setOpaque(false);

        lblBieuDo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/iconBieudo120px.png"))); // NOI18N
        lblBieuDo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBieuDo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBieuDoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBieuDoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBieuDoMousePressed(evt);
            }
        });

        lblBieudo_txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblBieudo_txt.setForeground(new java.awt.Color(255, 255, 255));
        lblBieudo_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBieudo_txt.setText("Thống Kê");
        lblBieudo_txt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpnBieuDo_ButtonLayout = new javax.swing.GroupLayout(jpnBieuDo_Button);
        jpnBieuDo_Button.setLayout(jpnBieuDo_ButtonLayout);
        jpnBieuDo_ButtonLayout.setHorizontalGroup(
            jpnBieuDo_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBieuDo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblBieudo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jpnBieuDo_ButtonLayout.setVerticalGroup(
            jpnBieuDo_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBieuDo_ButtonLayout.createSequentialGroup()
                .addComponent(lblBieuDo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBieudo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jpnMenu2Layout = new javax.swing.GroupLayout(jpnMenu2);
        jpnMenu2.setLayout(jpnMenu2Layout);
        jpnMenu2Layout.setHorizontalGroup(
            jpnMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenu2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jpnMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnHoaDon_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnKhachHang_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnBieuDo_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnMenu2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnNhaCungCap_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnMenu2Layout.setVerticalGroup(
            jpnMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenu2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jpnBieuDo_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnNhaCungCap_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnKhachHang_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnHoaDon_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jfMain.add(jpnMenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 200, 660));

        jpnMenu1.setOpaque(false);

        jpnBanHang_Button.setOpaque(false);

        lblBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/iconCaffe120px.png"))); // NOI18N
        lblBanHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBanHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBanHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBanHangMouseExited(evt);
            }
        });

        lblBanHang_txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblBanHang_txt.setForeground(new java.awt.Color(255, 255, 255));
        lblBanHang_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanHang_txt.setText("Bán Hàng");
        lblBanHang_txt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpnBanHang_ButtonLayout = new javax.swing.GroupLayout(jpnBanHang_Button);
        jpnBanHang_Button.setLayout(jpnBanHang_ButtonLayout);
        jpnBanHang_ButtonLayout.setHorizontalGroup(
            jpnBanHang_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblBanHang_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnBanHang_ButtonLayout.setVerticalGroup(
            jpnBanHang_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBanHang_ButtonLayout.createSequentialGroup()
                .addComponent(lblBanHang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBanHang_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpnKienTra_Button.setOpaque(false);

        lblKiemTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/iconKiemTraHang120px.png"))); // NOI18N
        lblKiemTra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblKiemTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblKiemTraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblKiemTraMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblKiemTraMousePressed(evt);
            }
        });

        lblKiemTraHangHoa_txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblKiemTraHangHoa_txt.setForeground(new java.awt.Color(255, 255, 255));
        lblKiemTraHangHoa_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKiemTraHangHoa_txt.setText("Kiểm Tra Hàng Hóa");
        lblKiemTraHangHoa_txt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpnKienTra_ButtonLayout = new javax.swing.GroupLayout(jpnKienTra_Button);
        jpnKienTra_Button.setLayout(jpnKienTra_ButtonLayout);
        jpnKienTra_ButtonLayout.setHorizontalGroup(
            jpnKienTra_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblKiemTra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblKiemTraHangHoa_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnKienTra_ButtonLayout.setVerticalGroup(
            jpnKienTra_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnKienTra_ButtonLayout.createSequentialGroup()
                .addComponent(lblKiemTra, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKiemTraHangHoa_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
        );

        jpnNhapHanghoa_Button.setOpaque(false);

        lblThemHangHoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/iconThemHang120px.png"))); // NOI18N
        lblThemHangHoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblThemHangHoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThemHangHoaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblThemHangHoaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThemHangHoaMouseExited(evt);
            }
        });

        lblthemHangHoa_txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblthemHangHoa_txt.setForeground(new java.awt.Color(255, 255, 255));
        lblthemHangHoa_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblthemHangHoa_txt.setText("Nhập \\Thêm Hàng Hóa");
        lblthemHangHoa_txt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpnNhapHanghoa_ButtonLayout = new javax.swing.GroupLayout(jpnNhapHanghoa_Button);
        jpnNhapHanghoa_Button.setLayout(jpnNhapHanghoa_ButtonLayout);
        jpnNhapHanghoa_ButtonLayout.setHorizontalGroup(
            jpnNhapHanghoa_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblThemHangHoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblthemHangHoa_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
        jpnNhapHanghoa_ButtonLayout.setVerticalGroup(
            jpnNhapHanghoa_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNhapHanghoa_ButtonLayout.createSequentialGroup()
                .addComponent(lblThemHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblthemHangHoa_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpnThemSP_Button.setOpaque(false);

        lblThemSanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThemSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/iconBaoCaoHang120px.png"))); // NOI18N
        lblThemSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblThemSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblThemSanPhamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThemSanPhamMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblThemSanPhamMousePressed(evt);
            }
        });

        lblThemsanPham_txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblThemsanPham_txt.setForeground(new java.awt.Color(255, 255, 255));
        lblThemsanPham_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThemsanPham_txt.setText("Thêm Sản Phẩm Mới");
        lblThemsanPham_txt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpnThemSP_ButtonLayout = new javax.swing.GroupLayout(jpnThemSP_Button);
        jpnThemSP_Button.setLayout(jpnThemSP_ButtonLayout);
        jpnThemSP_ButtonLayout.setHorizontalGroup(
            jpnThemSP_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblThemSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
            .addComponent(lblThemsanPham_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnThemSP_ButtonLayout.setVerticalGroup(
            jpnThemSP_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThemSP_ButtonLayout.createSequentialGroup()
                .addComponent(lblThemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblThemsanPham_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jpnMenu1Layout = new javax.swing.GroupLayout(jpnMenu1);
        jpnMenu1.setLayout(jpnMenu1Layout);
        jpnMenu1Layout.setHorizontalGroup(
            jpnMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenu1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jpnMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnThemSP_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnNhapHanghoa_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnBanHang_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnKienTra_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jpnMenu1Layout.setVerticalGroup(
            jpnMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnBanHang_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnKienTra_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnNhapHanghoa_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnThemSP_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jfMain.add(jpnMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 230, 660));

        jpnToolbar2.setBackground(new java.awt.Color(255, 255, 255));
        jpnToolbar2.setOpaque(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("-");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        lblOut.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/logout.png"))); // NOI18N
        lblOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblOutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblOutMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jpnToolbar2Layout = new javax.swing.GroupLayout(jpnToolbar2);
        jpnToolbar2.setLayout(jpnToolbar2Layout);
        jpnToolbar2Layout.setHorizontalGroup(
            jpnToolbar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnToolbar2Layout.createSequentialGroup()
                .addContainerGap(980, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblOut)
                .addGap(35, 35, 35))
        );
        jpnToolbar2Layout.setVerticalGroup(
            jpnToolbar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jfMain.add(jpnToolbar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/nenThuNgan.png"))); // NOI18N
        jfMain.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 760));

        add(jfMain, "card2");

        Card.setBackground(new java.awt.Color(255, 255, 255));
        Card.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Card.setLayout(new java.awt.CardLayout());
        add(Card, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void lblDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseClicked
        // TODO add your handling code here:
        FormLogin.login.Card.removeAll();
        FormLogin.login.Card.add(FormLogin.login.jfLogin);
        FormLogin.login.Card.repaint();
        FormLogin.login.Card.revalidate();
        FormLogin.login.Card.show();
        jfMain.hide();
        Login.jpnNenButton_login.setBackground(new Color(0, 0, 0));
        Login.jpnNenButton_login.setOpaque(false);
        Login.lblLogin.setForeground(Color.white);
        jpnDangXuat.setBackground(Color.white);
        lblDangXuat.setForeground(new Color(51, 102, 255));
        jpnShowMenuOut.hide();


    }//GEN-LAST:event_lblDangXuatMouseClicked

    private void lblDangXuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseEntered
        // TODO add your handling code here:

        jpnDangXuat.setBackground(new Color(51, 102, 255));
        lblDangXuat.setForeground(Color.white);
        jpnShowMenuOut.show();
    }//GEN-LAST:event_lblDangXuatMouseEntered

    private void lblDangXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseExited

        jpnDangXuat.setBackground(Color.white);
        lblDangXuat.setForeground(new Color(51, 102, 255));
    }//GEN-LAST:event_lblDangXuatMouseExited

    private void lblTenDangNhapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTenDangNhapMouseEntered
        // TODO add your handling code here:

        jpnTenDangNhap.setBackground(new Color(51, 102, 255));
        lblTenDangNhap.setForeground(Color.white);
        jpnShowMenuOut.show();
    }//GEN-LAST:event_lblTenDangNhapMouseEntered

    private void lblTenDangNhapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTenDangNhapMouseExited
        // TODO add your handling code here:

        jpnTenDangNhap.setBackground(Color.white);
        lblTenDangNhap.setForeground(new Color(51, 102, 255));

    }//GEN-LAST:event_lblTenDangNhapMouseExited

    private void jpnShowMenuOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnShowMenuOutMouseExited
        // TODO add your handling code here:
        jpnShowMenuOut.hide();
    }//GEN-LAST:event_jpnShowMenuOutMouseExited

    private void lblThemNhaCungCapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemNhaCungCapMouseEntered
        // TODO add your handling code here:
        jpnThemNhaCungCap_Button.setBackground(Color.WHITE);
        lblThemNhaCungCap_txt.setForeground(Color.BLACK);
        jpnThemNhaCungCap_Button.setOpaque(true);
    }//GEN-LAST:event_lblThemNhaCungCapMouseEntered

    private void lblThemNhaCungCapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemNhaCungCapMouseExited
        // TODO add your handling code here:
        jpnThemNhaCungCap_Button.setBackground(new Color(0, 0, 0));
        lblThemNhaCungCap_txt.setForeground(Color.white);
        jpnThemNhaCungCap_Button.setOpaque(false);
    }//GEN-LAST:event_lblThemNhaCungCapMouseExited

    private void lblSuaXoaSPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSuaXoaSPMouseEntered
        // TODO add your handling code here:
        jpnSuaXoaSP_Button.setBackground(Color.WHITE);
        lblSuaXoaSP_txt.setForeground(Color.BLACK);
        jpnSuaXoaSP_Button.setOpaque(true);
    }//GEN-LAST:event_lblSuaXoaSPMouseEntered

    private void lblSuaXoaSPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSuaXoaSPMouseExited
        // TODO add your handling code here:
        jpnSuaXoaSP_Button.setBackground(new Color(0, 0, 0));
        lblSuaXoaSP_txt.setForeground(Color.white);
        jpnSuaXoaSP_Button.setOpaque(false);
    }//GEN-LAST:event_lblSuaXoaSPMouseExited

    private void lblTaiKhoanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTaiKhoanMouseEntered
        // TODO add your handling code here:
        jpnTaiKhoan_Button.setBackground(Color.WHITE);
        lblTaiKhoan_txt.setForeground(Color.BLACK);
        jpnTaiKhoan_Button.setOpaque(true);
    }//GEN-LAST:event_lblTaiKhoanMouseEntered

    private void lblTaiKhoanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTaiKhoanMouseExited
        // TODO add your handling code here:
        jpnTaiKhoan_Button.setBackground(new Color(0, 0, 0));
        lblTaiKhoan_txt.setForeground(Color.white);
        jpnTaiKhoan_Button.setOpaque(false);
    }//GEN-LAST:event_lblTaiKhoanMouseExited

    private void lblQuanLyTaiKhoanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyTaiKhoanMouseEntered
        // TODO add your handling code here:
        jpnQuanLyTaiKhoan_Button.setBackground(Color.WHITE);
        lblQuanLyTaiKhoan_txt.setForeground(Color.BLACK);
        jpnQuanLyTaiKhoan_Button.setOpaque(true);
    }//GEN-LAST:event_lblQuanLyTaiKhoanMouseEntered

    private void lblQuanLyTaiKhoanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyTaiKhoanMouseExited
        // TODO add your handling code here:
        jpnQuanLyTaiKhoan_Button.setBackground(new Color(0, 0, 0));
        lblQuanLyTaiKhoan_txt.setForeground(Color.white);
        jpnQuanLyTaiKhoan_Button.setOpaque(false);
    }//GEN-LAST:event_lblQuanLyTaiKhoanMouseExited

    private void lblSuaHangHoa_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSuaHangHoa_ButtonMouseEntered
        // TODO add your handling code here:
        jpnSuaHangHoa_Button.setBackground(Color.WHITE);
        lblSuaHangHoa_txt.setForeground(Color.BLACK);
        jpnSuaHangHoa_Button.setOpaque(true);
    }//GEN-LAST:event_lblSuaHangHoa_ButtonMouseEntered

    private void lblSuaHangHoa_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSuaHangHoa_ButtonMouseExited
        // TODO add your handling code here:
        jpnSuaHangHoa_Button.setBackground(new Color(0, 0, 0));
        jpnSuaHangHoa_Button.setOpaque(false);
        lblSuaHangHoa_txt.setForeground(Color.white);
    }//GEN-LAST:event_lblSuaHangHoa_ButtonMouseExited

    private void lblPhieuNhapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhieuNhapMouseEntered
        // TODO add your handling code here:
        jpnPhieuNhap_Button.setBackground(Color.WHITE);
        lblPhieuNhap_txt.setForeground(Color.BLACK);
        jpnPhieuNhap_Button.setOpaque(true);
    }//GEN-LAST:event_lblPhieuNhapMouseEntered

    private void lblPhieuNhapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhieuNhapMouseExited
        // TODO add your handling code here:
        jpnPhieuNhap_Button.setBackground(new Color(0, 0, 0));
        jpnPhieuNhap_Button.setOpaque(false);
        lblPhieuNhap_txt.setForeground(Color.white);
    }//GEN-LAST:event_lblPhieuNhapMouseExited

    private void lblNhacungcapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhacungcapMouseEntered
        // TODO add your handling code here:
        jpnNhaCungCap_Button.setBackground(Color.WHITE);
        lblNhaCungCap_txt.setForeground(Color.BLACK);
        jpnNhaCungCap_Button.setOpaque(true);
    }//GEN-LAST:event_lblNhacungcapMouseEntered

    private void lblNhacungcapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhacungcapMouseExited
        // TODO add your handling code here:
        jpnNhaCungCap_Button.setBackground(new Color(0, 0, 0));
        jpnNhaCungCap_Button.setOpaque(false);
        lblNhaCungCap_txt.setForeground(Color.white);
    }//GEN-LAST:event_lblNhacungcapMouseExited

    private void lblKhachHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhachHangMouseEntered
        // TODO add your handling code here:
        jpnKhachHang_Button.setBackground(Color.WHITE);
        lblKhachHang_txt.setForeground(Color.BLACK);
        jpnKhachHang_Button.setOpaque(true);
    }//GEN-LAST:event_lblKhachHangMouseEntered

    private void lblKhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhachHangMouseExited
        // TODO add your handling code here:

        jpnKhachHang_Button.setBackground(new Color(0, 0, 0));
        jpnKhachHang_Button.setOpaque(false);
        lblKhachHang_txt.setForeground(Color.white);
    }//GEN-LAST:event_lblKhachHangMouseExited

    private void lblHoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHoaDonMouseEntered
        // TODO add your handling code here:
        jpnHoaDon_Button.setBackground(Color.WHITE);
        lblHoaDon_txt.setForeground(Color.BLACK);
        jpnHoaDon_Button.setOpaque(true);
    }//GEN-LAST:event_lblHoaDonMouseEntered

    private void lblHoaDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHoaDonMouseExited
        // TODO add your handling code here:
        jpnHoaDon_Button.setBackground(new Color(0, 0, 0));
        jpnHoaDon_Button.setOpaque(false);
        lblHoaDon_txt.setForeground(Color.white);
    }//GEN-LAST:event_lblHoaDonMouseExited

    private void lblBieuDoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBieuDoMouseEntered
        // TODO add your handling code here:
        jpnBieuDo_Button.setBackground(Color.WHITE);
        lblBieudo_txt.setForeground(Color.BLACK);
        jpnBieuDo_Button.setOpaque(true);
    }//GEN-LAST:event_lblBieuDoMouseEntered

    private void lblBieuDoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBieuDoMouseExited
        // TODO add your handling code here:
        jpnBieuDo_Button.setBackground(new Color(0, 0, 0));
        jpnBieuDo_Button.setOpaque(false);
        lblBieudo_txt.setForeground(Color.white);
    }//GEN-LAST:event_lblBieuDoMouseExited

    private void lblBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanHangMouseClicked
        // TODO add your handling code here:
        FormLogin.login.Card.removeAll();
        FormLogin.login.Card.add(new FormBanHang());
        FormLogin.login.Card.repaint();
        FormLogin.login.Card.revalidate();
        FormLogin.login.Card.show();
        //mp3 = new Soundhelper("src/QLBHcafe/mp3/Night-Of-The-Piano.mp3");
//        mp3.play();
        jfMain.hide();

        // jpnMenOutBanHang.hide();

    }//GEN-LAST:event_lblBanHangMouseClicked

    private void lblBanHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanHangMouseEntered
        // TODO add your handling code here:

        jpnBanHang_Button.setBackground(Color.WHITE);
        jpnBanHang_Button.setOpaque(true);
        lblBanHang_txt.setForeground(Color.BLACK);

    }//GEN-LAST:event_lblBanHangMouseEntered

    private void lblBanHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanHangMouseExited
        // TODO add your handling code here:
        jpnBanHang_Button.setBackground(new Color(0, 0, 0));
        jpnBanHang_Button.setOpaque(false);
        lblBanHang_txt.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblBanHangMouseExited

    private void lblKiemTraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKiemTraMouseEntered
        // TODO add your handling code here:
        jpnKienTra_Button.setBackground(Color.WHITE);
        jpnKienTra_Button.setOpaque(true);
        lblKiemTraHangHoa_txt.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblKiemTraMouseEntered

    private void lblKiemTraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKiemTraMouseExited
        // TODO add your handling code here:
        jpnKienTra_Button.setBackground(new Color(0, 0, 0));
        jpnKienTra_Button.setOpaque(false);
        lblKiemTraHangHoa_txt.setForeground(Color.white);
    }//GEN-LAST:event_lblKiemTraMouseExited

    private void lblThemHangHoaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemHangHoaMouseEntered
        // TODO add your handling code here:
        jpnNhapHanghoa_Button.setBackground(Color.WHITE);
        jpnNhapHanghoa_Button.setOpaque(true);
        lblthemHangHoa_txt.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblThemHangHoaMouseEntered

    private void lblThemHangHoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemHangHoaMouseExited
        // TODO add your handling code here:
        jpnNhapHanghoa_Button.setBackground(new Color(0, 0, 0));
        jpnNhapHanghoa_Button.setOpaque(false);
        lblthemHangHoa_txt.setForeground(Color.white);
    }//GEN-LAST:event_lblThemHangHoaMouseExited

    private void lblThemSanPhamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemSanPhamMouseEntered
        // TODO add your handling code here:
        jpnThemSP_Button.setBackground(Color.WHITE);
        lblThemsanPham_txt.setForeground(Color.BLACK);
        jpnThemSP_Button.setOpaque(true);
    }//GEN-LAST:event_lblThemSanPhamMouseEntered

    private void lblThemSanPhamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemSanPhamMouseExited
        // TODO add your handling code here:
        jpnThemSP_Button.setBackground(new Color(0, 0, 0));
        jpnThemSP_Button.setOpaque(false);
        lblThemsanPham_txt.setForeground(Color.white);
    }//GEN-LAST:event_lblThemSanPhamMouseExited

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        // setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void lblOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOutMouseClicked
        // TODO add your handling code here:

        /**/
        jpnShowMenuOut.show();
        lblOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/logout.png")));
    }//GEN-LAST:event_lblOutMouseClicked

    private void lblOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOutMouseEntered
        // TODO add your handling code here:

        lblOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/logout_hover.png")));
    }//GEN-LAST:event_lblOutMouseEntered

    private void lblOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOutMouseExited
        // TODO add your handling code here:
        lblOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/logout.png")));
    }//GEN-LAST:event_lblOutMouseExited

    private void lblOutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOutMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_lblOutMousePressed

    private void lblOutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOutMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblOutMouseReleased

    private void lblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhachHangMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_lblKhachHangMouseClicked

    private void lblThemHangHoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemHangHoaMouseClicked
        // TODO add your handling code here:
        FormLogin.login.Card.removeAll();
        FormLogin.login.Card.add(new FormNhapThemHangHoa());
        FormLogin.login.Card.repaint();
        FormLogin.login.Card.revalidate();
        FormLogin.login.Card.show();
        jfMain.hide();
    }//GEN-LAST:event_lblThemHangHoaMouseClicked

    private void lblKiemTraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKiemTraMousePressed
        // TODO add your handling code here:
        FormLogin.login.Card.removeAll();
        FormLogin.login.Card.add(new FormKiemTraHangHoa());
        FormLogin.login.Card.repaint();
        FormLogin.login.Card.revalidate();
        FormLogin.login.Card.show();
        jfMain.hide();

    }//GEN-LAST:event_lblKiemTraMousePressed

    private void lblSuaHangHoa_ButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSuaHangHoa_ButtonMousePressed
        // TODO add your handling code here:
        FormLogin.login.Card.removeAll();
        FormLogin.login.Card.add(new FormSuaHangHoa_admin());
        FormLogin.login.Card.repaint();
        FormLogin.login.Card.revalidate();
        FormLogin.login.Card.show();
        jfMain.hide();

    }//GEN-LAST:event_lblSuaHangHoa_ButtonMousePressed

    private void lblThemSanPhamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemSanPhamMousePressed
        // TODO add your handling code here:
        FormLogin.login.Card.removeAll();
        FormLogin.login.Card.add(new FormThemSanPham());
        FormLogin.login.Card.repaint();
        FormLogin.login.Card.revalidate();
        FormLogin.login.Card.show();
        jfMain.hide();
    }//GEN-LAST:event_lblThemSanPhamMousePressed

    private void lblBieuDoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBieuDoMousePressed
        // TODO add your handling code here:
        FormLogin.login.Card.removeAll();
        FormLogin.login.Card.add(new FormThongKe());
        FormLogin.login.Card.repaint();
        FormLogin.login.Card.revalidate();
        FormLogin.login.Card.show();
        jfMain.hide();
    }//GEN-LAST:event_lblBieuDoMousePressed

    private void lblNhacungcapMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhacungcapMousePressed
        // TODO add your handling code here:
        FormLogin.login.Card.removeAll();
        FormLogin.login.Card.add(new FormDanhSachNhaCC());
        FormLogin.login.Card.repaint();
        FormLogin.login.Card.revalidate();
        FormLogin.login.Card.show();
        jfMain.hide();
    }//GEN-LAST:event_lblNhacungcapMousePressed

    private void lblKhachHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhachHangMousePressed
        // TODO add your handling code here:
        FormLogin.login.Card.removeAll();
        FormLogin.login.Card.add(new FormKhachHang());
        FormLogin.login.Card.repaint();
        FormLogin.login.Card.revalidate();
        FormLogin.login.Card.show();
        jfMain.hide();
    }//GEN-LAST:event_lblKhachHangMousePressed

    private void lblHoaDonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHoaDonMousePressed
        // TODO add your handling code here:
        FormLogin.login.Card.removeAll();
        FormLogin.login.Card.add(new FormDonHang());
        FormLogin.login.Card.repaint();
        FormLogin.login.Card.revalidate();
        FormLogin.login.Card.show();
        jfMain.hide();
    }//GEN-LAST:event_lblHoaDonMousePressed

    private void lblTaiKhoanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTaiKhoanMousePressed
        // TODO add your handling code here:
        FormLogin.login.Card.removeAll();
        FormLogin.login.Card.add(new FormTaiKhoan());
        FormLogin.login.Card.repaint();
        FormLogin.login.Card.revalidate();
        FormLogin.login.Card.show();
        jfMain.hide();
    }//GEN-LAST:event_lblTaiKhoanMousePressed

    private void lblQuanLyTaiKhoanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyTaiKhoanMousePressed
        // TODO add your handling code here:
        FormLogin.login.Card.removeAll();
        FormLogin.login.Card.add(new FormQuanLyTaiKhoan_admin());
        FormLogin.login.Card.repaint();
        FormLogin.login.Card.revalidate();
        FormLogin.login.Card.show();
        jfMain.hide();
    }//GEN-LAST:event_lblQuanLyTaiKhoanMousePressed

    private void lblPhieuNhapMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhieuNhapMousePressed
        // TODOFormLogin.login.Card.removeAll();
        FormLogin.login.Card.removeAll();
        FormLogin.login.Card.add(new FormQuanLyPhieuNhap_admin());
        FormLogin.login.Card.repaint();
        FormLogin.login.Card.revalidate();
        FormLogin.login.Card.show();
        jfMain.hide();
    }//GEN-LAST:event_lblPhieuNhapMousePressed

    private void lblSuaXoaSPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSuaXoaSPMousePressed
        // TODO add your handling code here:
        FormLogin.login.Card.removeAll();
        FormLogin.login.Card.add(new FormSuaHangHoa_admin());
        FormLogin.login.Card.repaint();
        FormLogin.login.Card.revalidate();
        FormLogin.login.Card.show();
        jfMain.hide();

    }//GEN-LAST:event_lblSuaXoaSPMousePressed

    private void lblThemNhaCungCapMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemNhaCungCapMousePressed
        // TODO add your handling code here:
        FormLogin.login.Card.removeAll();
        FormLogin.login.Card.add(new FormThemNhaCungCap_admin());
        FormLogin.login.Card.repaint();
        FormLogin.login.Card.revalidate();
        FormLogin.login.Card.show();
        jfMain.hide();
    }//GEN-LAST:event_lblThemNhaCungCapMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected static javax.swing.JPanel Card;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    public static javax.swing.JPanel jfMain;
    private javax.swing.JLabel jlbLogo150px2;
    private javax.swing.JPanel jpnBanHang_Button;
    private javax.swing.JPanel jpnBieuDo_Button;
    private javax.swing.JPanel jpnDangXuat;
    private javax.swing.JPanel jpnHoaDon_Button;
    private javax.swing.JPanel jpnKhachHang_Button;
    private javax.swing.JPanel jpnKienTra_Button;
    private javax.swing.JPanel jpnMenu1;
    private javax.swing.JPanel jpnMenu2;
    private javax.swing.JPanel jpnMenu3;
    private javax.swing.JPanel jpnMenu4;
    private javax.swing.JPanel jpnNhaCungCap_Button;
    private javax.swing.JPanel jpnNhapHanghoa_Button;
    private javax.swing.JPanel jpnPhieuNhap_Button;
    private javax.swing.JPanel jpnQuanLyTaiKhoan_Button;
    private javax.swing.JPanel jpnShowMenuOut;
    private javax.swing.JPanel jpnSuaHangHoa_Button;
    private javax.swing.JPanel jpnSuaXoaSP_Button;
    private javax.swing.JPanel jpnTaiKhoan_Button;
    private javax.swing.JPanel jpnTenDangNhap;
    private javax.swing.JPanel jpnThemNhaCungCap_Button;
    private javax.swing.JPanel jpnThemSP_Button;
    private javax.swing.JPanel jpnToolbar2;
    private javax.swing.JLabel lblBanHang;
    private javax.swing.JLabel lblBanHang_txt;
    private javax.swing.JLabel lblBieuDo;
    private javax.swing.JLabel lblBieudo_txt;
    private javax.swing.JLabel lblDangXuat;
    private javax.swing.JLabel lblHoaDon;
    private javax.swing.JLabel lblHoaDon_txt;
    private javax.swing.JLabel lblKhachHang;
    private javax.swing.JLabel lblKhachHang_txt;
    private javax.swing.JLabel lblKiemTra;
    private javax.swing.JLabel lblKiemTraHangHoa_txt;
    private javax.swing.JLabel lblNhaCungCap_txt;
    private javax.swing.JLabel lblNhacungcap;
    private javax.swing.JLabel lblOut;
    private javax.swing.JLabel lblPhieuNhap;
    private javax.swing.JLabel lblPhieuNhap_txt;
    private javax.swing.JLabel lblQuanLyTaiKhoan;
    private javax.swing.JLabel lblQuanLyTaiKhoan_txt;
    private javax.swing.JLabel lblSuaHangHoa_Button;
    private javax.swing.JLabel lblSuaHangHoa_txt;
    private javax.swing.JLabel lblSuaXoaSP;
    private javax.swing.JLabel lblSuaXoaSP_txt;
    private javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JLabel lblTaiKhoan_txt;
    private javax.swing.JLabel lblTenDangNhap;
    private javax.swing.JLabel lblThemHangHoa;
    private javax.swing.JLabel lblThemNhaCungCap;
    private javax.swing.JLabel lblThemNhaCungCap_txt;
    private javax.swing.JLabel lblThemSanPham;
    private javax.swing.JLabel lblThemsanPham_txt;
    private javax.swing.JLabel lblthemHangHoa_txt;
    // End of variables declaration//GEN-END:variables
}
